
services:
  mysql:
    image: mysql:8.0
    container_name: hris_mysql
    environment:
      MYSQL_DATABASE: PBL_CMLabs
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - hris_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hris_backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: PBL_CMLabs
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      HOME: /tmp
    volumes:
      - ./backend/laravel:/var/www/html
      - ./backend/laravel/.env:/var/www/html/.env
    user: "${UID}:${GID}"
    networks:
      - hris_network

  frontend:
    build:
      context: ./frontend
    container_name: hris_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://pblcmlabs.duckdns.org/api
    depends_on:
      - backend
    volumes:
      - ./frontend/.env.local:/app/.env.local
    networks:
      - hris_network

  portainer:
    image: portainer/portainer-ce
    container_name: hris_portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - hris_network

volumes:
  mysql_data:
  portainer_data:

networks:
  hris_network:
